---
title: "Data Citation with only a top-level Online Link"
author: 
  - "Lars Vilhuber"
categories: [data citation, FAQ, website, URL, OECD, Census Bureau]
aliases:
  - "/FAQ.html#data-citation-toplevel-link"
---
Many databases with an online interface make it hard to find an easy-to-cite URL. Nevertheless, a few clicks can often show a referenceable URL. Here's an example: 

## OECD Statistics

The top-level URL is [https://stats.oecd.org/](https://stats.oecd.org/), and (almost) never changes. However, the [User Guide](https://stats.oecd.org/Content/themes/OECD/static/help/WBOS%20User%20Guide%20(EN).PDF?page=34), page 34, shows how to share a URL for a particular query. The usual citation rules for URLs then can be applied.

## Data.census.gov

The top-level URL is [https://data.census.gov/](https://data.census.gov/). There are several million tables behind the website. However, for any given table and view, one can click on the "More Tools" at the top right, and get a citation. This will point to the exact table you are viewing. 

Example:

> U.S. Census Bureau, U.S. Department of Commerce. "Households and Families." American Community Survey, ACS 1-Year Estimates Subject Tables, Table S1101, https://data.census.gov/table/ACSST1Y2023.S1101?q=same-gender+household. Accessed on 23 Aug 2025.