---
title: "Data Citation without Online Link"
author: 
  - "Lars Vilhuber"
categories: [data citation, FAQ, proprietary data, no URL, offline, unpublished]
---

> Do you have any examples of data citation for proprietary data that does not have an online link? All the examples are much more formal than the random spreadsheets [agency 1]  sent over! [agency 2] has a more formal naming system, but again, there's no persistent indicator for the datasets because they are not accessible.

A known problem with no clear solution. Here's how I try to approach the problem:

 - A citation has author, title, and a publisher, with optional other locators. (see [Chicago Manual of Style (subscription)](https://www.chicagomanualofstyle.org/book/ed17/part3/ch14/psec014.html) and [CMS Quick Guide on citations](https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-2.html). 
 
Note that Chicago-style does not actually require the locator information - see the examples for "E-book" Kindle.
 
> "Electronic content presented without formal ties to a publisher or sponsoring body has the authority equivalent to that of unpublished or self-published material in other media."

Thus, one can construct the citation as
    - Author: the provider of the data (the agency)
    - Title: whatever the provider would recognize and re-furnish to a third-party
    - Publisher: the provider of the data (or its higher-level institution, e.g., the government department or ministry)
    - Locators (optional): maybe something along the lines of "Multiple electronic files" with possible additional information ", provided to the author under DUA (date or any contract number)"

An example might thus be:

> Agency 1. 2007. *Name of DataSet*. Boston: Commonwealth of Massachusetts. Multiple electronic files.

For more information, see the [AEA Data Editor's guidance on Data Citations](https://aeadataeditor.github.io/aea-de-guidance/addtl-data-citation-guidance.html).