---
layout: withtoc
title: Data Availability Statements for Commercial Data
---

Many economics papers use data from individual private companies, as well as from commercial data aggregators. Generally, these data cannot be redistributed by the author of a paper. Usage rights must be acquired from the original provider. This is not dissimilar from restricted data from statistical agencies, though there is significantly more variation in access procedures and cost.

This page uses a few examples, and suggested descriptions of data access for these examples. If you have an example to suggest for this page, send an email to dataeditor@aeaweb.org or [create a pull request](https://github.com/social-science-data-editors/guidance/pulls/new).

> NOTE: Nothing on this page should be construed as official or legal advice. Always consult with your data provider.

### Compustat®
Compustat data is often used in macroeconomic or industrial organization papers. Compustat is owned by S&P Global.

- Data access description: Researchers can subscribe to the data. Many universities and research institutions have such a subscription. 
-  URL with more info on data access: 
[https://www.spglobal.com/marketintelligence/en/client-segments/academia](https://www.spglobal.com/marketintelligence/en/client-segments/academia)
- Possible Data Access Statement (no guarantees):

> Compustat is owned by S&P Global. Researchers can subscribe to the data. Many universities and research institutions have such a subscription. More info on data access for academia can be found at https://www.spglobal.com/marketintelligence/en/client-segments/academia .

- Ability to redistribute extracts: Unknown
- Ability to redistribute aggregated data: Unknown
- Examples in the literature:
  - To come ([create a pull request](https://github.com/social-science-data-editors/guidance/pulls/new))

### Nielsen 

The [Nielsen Company](http://www.nielsen.com/us/en.html) provides various datasets through the Chicago Booth's [Kilts Center for Marketing](https://www.chicagobooth.edu/research/kilts/).

- Data access description: Researchers can subscribe to the data through the Kilts Center. There is a cost.

- As per the Kilts Center's policies (https://www.chicagobooth.edu/research/kilts/datasets/nielsen/policies), presentations, papers, and publications must include the following citation:

>“Researcher(s) own analyses calculated (or derived) based in part on data from The Nielsen Company (US), LLC and marketing databases provided through the Nielsen Datasets at the Kilts Center for Marketing Data Center at The University of Chicago Booth School of Business.”

>“The conclusions drawn from the Nielsen data are those of the researcher(s) and do not reflect the views of Nielsen. Nielsen is not responsible for, had no role in, and was not involved in analyzing and preparing the results reported herein.”

Adding those paragraphs into the title page footnote has been found to be sufficient in past papers (see Kilts Center SSRN).

- Ability to redistribute extracts: Unknown
- Ability to redistribute aggregated data: Unknown

#### Examples in the literature:
  - To come ([create a pull request](https://github.com/social-science-data-editors/guidance/pulls/new))

### S&P 500

The S&P 500 is one of the most widely known stock indexes. And yet, it is subject to copyright, and restrictions on redistribution.

 Many authors who use the S&P 500 numbers may have downloaded it via FRED [https://fred.stlouisfed.org/series/SP500](https://fred.stlouisfed.org/series/SP500) or through other data services (Haver Analytics, Bloomberg).The FRED website mentions that the data are 
 
 > &copy; S&P Dow Jones Indices LLC. Reproduction of S&P 500 in any form is prohibited except with the prior written permission of S&P Dow Jones Indices LLC ("S&P").

It seems to be possible to request permission to distribute the extracts, using this form, or by sending email to 

Most analyses will have a longer historical time horizon than the 10 years available through FRED, but will publish with a typical lag of 15-20 months.

#### Citation

If obtained through FRED, the suggested citation is

> S&P Dow Jones Indices LLC, *S&P 500 [SP500]*, retrieved from FRED, Federal Reserve Bank of St. Louis; https://fred.stlouisfed.org/series/SP500, January 24, 2020. 

An analogue if accessing it through, say, Haver Analytics, might be

> S&P Dow Jones Indices LLC, *S&P 500*, provided via Haver Analytics, January 24, 2020. 

#### Data Availability Statement

> S&P 500 data is (C) S&P Dow Jones Indices LLC. Reproduction of S&P 500 in any form is prohibited except with the prior written permission of S&P Dow Jones Indices LLC ("S&P"). It is thus not available as part of the replication archive. Users may access the past 10 years via FRED at [https://fred.stlouisfed.org/series/SP500](https://fred.stlouisfed.org/series/SP500), or purchase longer access via Haver Analytics ([http://www.haver.com/databaseprofiles.html#indicators](http://www.haver.com/databaseprofiles.html#indicators)). Note that reproduction of our manuscript's tables requires data from [YYYY]-[ZZZZ]. 

#### Examples in the literature:

- To come ([create a pull request](https://github.com/social-science-data-editors/guidance/pulls/new))


### Ethnologue data

> The Ethnologue database contains maps and other information on languages in the world. Subscriptions are available at https://www.ethnologue.com/pricing. Academic rebates are available. 

Ethnologue have been known to provide permission to redistribute extracts for the purposes of replication. 

#### Citation

> Eberhard, David M., Gary F. Simons, and Charles D. Fennig (eds.). 2019. *Ethnologue: Languages of the World. Twenty-second edition.* Dallas, Texas: SIL International. Online version: http://www.ethnologue.com

#### Examples in the literature:

- To come ([create a pull request](https://github.com/social-science-data-editors/guidance/pulls/new))

