FROM ruby:2.7

RUN bundle config --global frozen 1

WORKDIR /usr/src/app

# prepare to install ruby packages into container
COPY Gemfile Gemfile.lock jekyll-theme-minimal.gemspec ./

RUN gem install bundler
RUN bundle config unset frozen
RUN bundle install

VOLUME /usr/src/app

EXPOSE 4000

CMD jekyll serve /_site --watch --force_polling -H 0.0.0.0 -P 4000
#CMD /bin/bash