# Sample letter to request data for publication and/or sharing

Dear <ACCOUNT REP>, 

I hope you can help me with this or, if not, direct me to the appropriate person at <PUBLISHER/PROVIDER> who can.

I[, along with two collaborators,] have used the [PROPRIETARY DATA] in an academic study that has been accepted for publication by the [JOURNAL], a publication of the [PUBLISHER]. The exact series we used are referenced below. The data were purchased from <PUBLISHER> on <PURCHASE DATE>. 

The [JOURNAL/PUBLISHER] has a data and code availability policy, requiring that authors deposit all accessible data in an open trusted repository.  The [JOURNAL]'s Data Editor has requested the following information:

-    Can the data extract we used (specifically, [NAME DATA ELEMENTS HERE]) be published as part of the [JOURNAL]'s Repository at [URL FOR REPOSITORY] with an open license?
-   If not, can the data extract be published as a restricted data set (example, see [openICPSR FAQ](https://www.openicpsr.org/openicpsr/faqs)). [Example:] Access would be restricted to academics, and can include prohibition of subsequent downloads.
-   If the data have already been archived and preserved at a data archive with a CoreTrustSeal or equivalent certification, can you provide us with the DOI for such data?

Independent of the above distribution requests,

-    are we allowed to share the data with the [JOURNAL]'s Data Editor for reproducibility checks, without subsequent publication. The Data Editor will use the data to assess the computational reproducibility of the paper, and subsequently destroy the data.


Thank you in advance for your attention to this matter. 

[AUTHOR]

